(setq jc-init-dir "~/.emacs.d/init.d")
(when (file-exists-p jc-init-dir)
  (dolist (file (directory-files jc-init-dir t "\.el$"))
    (let ((compiled-file (concat file "c")))
      (when (not (file-exists-p compiled-file))
	(byte-compile-file file))
      (load compiled-file))))
