(source gnu)
(source marmalade)
(source melpa)

(depends-on "ag")
(depends-on "aggressive-indent")
(depends-on "auto-compile")
(depends-on "bundler")
(depends-on "comment-dwim-2")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "duplicate-thing")
(depends-on "el-presenti" :git "https://github.com/jcinnamond/el-presenti")
(depends-on "embrace")
(depends-on "fill-column-indicator")
(depends-on "find-file-in-project")
(depends-on "flycheck")
(depends-on "gitconfig-mode")
(depends-on "github-browse-file")
(depends-on "gitignore-mode")
(depends-on "guide-key")
(depends-on "iedit")
(depends-on "ivy-hydra")
(depends-on "jc-movements" :git "https://github.com/jcinnamond/jc-movements")
(depends-on "jc-ruby-extra" :git "https://github.com/jcinnamond/jc-ruby-extra")
(depends-on "magit")
(depends-on "move-text")
(depends-on "multiple-cursors")
(depends-on "pair-mode" :git "https://github.com/jcinnamond/pair-mode")
(depends-on "pallet")
(depends-on "paradox")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "rbenv")
(depends-on "rspec-mode")
(depends-on "rubocop")
(depends-on "seeing-is-believing")
(depends-on "smart-mode-line")
(depends-on "smart-mode-line-powerline-theme")
(depends-on "swiper")
(depends-on "toggle-quotes")
(depends-on "use-package")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
